#TP2 de Ameur, le 08/11/2025
#print("Salem Ahmed")#"salem" c'est du String = STR= text
a=3#a variable
b=5#b variable
a=1
b=4
a=0
print("a=",a)#affiche moi la valeur de a sous forme a=...
print("b=",b)#affiche moi la valeur de b sous forme b=...
print("a+b=",a+b)#affiche moi la valeur de a+b sous forme a+b=...
a=2
print("a=",a)#affiche moi la valeur de a sous forme a=...
print("a-b=",a-b)#affiche moi la valeur de a-b sous forme a-b=...